name: New comment

on:
  issue_comment:
    types:
    - created

jobs:
  new_comment:
    name: New comment
    runs-on: ubuntu-latest
    if: github.actor != 'DorpsGek'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt
    - name: New comment
      run: |
        python -m request_access --new-comment
      env:
        GITHUB_TOKEN: ${{ secrets.DORPSGEK_TOKEN }}
