name: New issue

on:
  issues:
    types:
    - opened

jobs:
  new_issue:
    name: New issue
    runs-on: ubuntu-latest
    if: github.actor != 'DorpsGek'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt
    - name: New issue
      run: |
        python -m request_access --new-issue
      env:
        GITHUB_TOKEN: ${{ secrets.DORPSGEK_TOKEN }}
